### ISSUE TITLE
zh-CN Translate Submit

### ISSUE THREAD

**Issue by Meteorite1014** [TheMysticSword/Skillsmas#10]
I translated it into my native language.
Since Github does not support the .language suffix, I uploaded it with the .txt suffix.
[zh-CN.txt](https://github.com/TheMysticSword/Skillsmas/files/13886944/zh-CN.txt)

**Comment by TheMysticSword** [comment]
Merged your PR! The translation will be added in the latest update, which should be coming out shortly.
